### ISSUE TITLE
Unable to run the project

### ISSUE THREAD

**Issue by schakka22** [typedbyte/Chess.NET#1]
Cannot start the project as the output type is class library.
How do I fix this issue?

**Comment by typedbyte** [comment]
The code consists of three projects: `Chess.Model` and `Chess.ViewModel` are indeed class libraries, but `Chess.View` is executable (see [here](https://github.com/typedbyte/Chess.NET/blob/3215837c7c0c31bd93dee43cc1220309d5bfd611/Chess.View/Chess.View.csproj#L4)) and this is the one you should start.
